<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:msg="http://xsdInternalChanges/v001"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:srv="http://XsdInternalChanges/v001"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        name="WSDLInternalChanges_v001"
        targetNamespace="http://XsdInternalChanges/v001">

    <wsdl:types>
        <xsd:schema>
            <xsd:import namespace="http://xsdInternalChanges/v001" schemaLocation="XsdInternalChangesV1.xsd"/>
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="getDefinitionsRequest">
        <wsdl:part element="msg:simpleDescription" name="getDefinitionsRequest"/>
    </wsdl:message>
    <wsdl:message name="getDefinitionsResponse">
        <wsdl:part element="msg:simpleDescription" name="getDefinitionsResponse"/>
    </wsdl:message>

    <wsdl:portType name="IWSDLInternalChanges">
        <wsdl:operation name="getDefinitions">
            <wsdl:input message="srv:getDefinitionsRequest"/>
            <wsdl:output message="srv:getDefinitionsResponse"/>
        </wsdl:operation>
        <wsdl:operation name="toBeRemoved">

            <wsdl:input message="srv:getDefinitionsRequest"/>
            <wsdl:output message="srv:getDefinitionsResponse"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="WSDLInternalChanges_soaphttp" type="srv:IWSDLInternalChanges">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="getDefinitions">
            <soap:operation soapAction="http://xmlns.telenet.be/soa.model/services/common/channel/MigrationChannelService/FullMVNOMigrationChannelService/v001/bulkScheduleFullMvnoMigration"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="WSDLInternalChangesService">
        <wsdl:port binding="WSDLInternalChanges_soaphttp" name="WSDLInternalChanges_soaphttp">
            <soap:address location="http://localhost:7001/WSDLInternalChangesService/ProxyServices/WSDLInternalChangesService_PS_v001/"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>